export const productosPorCategoria: Record<string, { nombre: string; link: string; imagen: string; precio: string }[]> = {
  plomeria: [
    { nombre: "Teflon", link: "https://meli.la/2Kp9P1p", imagen: "/herramientas/teflon.webp", precio: "$5.058" },
    { nombre: "Desatascador sopapa", link: "https://meli.la/23xTGSU", imagen: "/herramientas/sopapa.webp", precio: "$3.610" },
    { nombre: "Llave de paso", link: "https://meli.la/2neG1fw", imagen: "/herramientas/llave-de-paso.webp", precio: "$42.010" },
    { nombre: "Arandelas y gomas", link: "https://meli.la/19NwokA", imagen: "/herramientas/arandelas.webp", precio: "$27.500" },
    { nombre: "Cinta autofusionante", link: "https://meli.la/172H5z3", imagen: "/herramientas/cinta-autofusionante.webp", precio: "$7.200" },
    { nombre: "Llave stillson", link: "https://meli.la/1qAqJ1X", imagen: "/herramientas/llave-stillson.webp", precio: "$51.264" },
    { nombre: "Silicona selladora", link: "https://meli.la/19YK9Yj", imagen: "/herramientas/silicona.webp", precio: "$12.207" },
    { nombre: "Flexible de conexion", link: "https://meli.la/1n84vfm", imagen: "/herramientas/flexible.webp", precio: "$7.574" },
  ],
  electricidad: [
    { nombre: "Multimetro tester", link: "https://meli.la/1HUtoEH", imagen: "/herramientas/multimetro.webp", precio: "$18.799" },
    { nombre: "Cinta aisladora", link: "https://meli.la/1dET9i2", imagen: "/herramientas/cinta-aisladora.webp", precio: "$12.231" },
    { nombre: "Llave de luz simple", link: "https://meli.la/2rtNU2B", imagen: "/herramientas/llave-luz.webp", precio: "$33.820" },
    { nombre: "Tomacorriente", link: "https://meli.la/1vKqafS", imagen: "/herramientas/tomacorriente.webp", precio: "$34.400" },
    { nombre: "Cable unipolar 2.5mm", link: "https://meli.la/2BQHPXG", imagen: "/herramientas/cable-unipolar.webp", precio: "$51.400" },
    { nombre: "Termica disyuntor", link: "https://meli.la/33fygpp", imagen: "/herramientas/termica.webp", precio: "$41.334" },
    { nombre: "Lampara LED", link: "https://meli.la/28k1YA4", imagen: "/herramientas/lampara-led.webp", precio: "$29.549" },
    { nombre: "Pinza amperometrica", link: "https://meli.la/2NoxPkz", imagen: "/herramientas/pinza-amperometrica.webp", precio: "$42.399" },
  ],
  carpinteria: [
    { nombre: "Bisagras", link: "https://meli.la/2HRetLK", imagen: "/herramientas/bisagras.webp", precio: "$18.832" },
    { nombre: "Lija al agua", link: "https://meli.la/2sLkdeP", imagen: "/herramientas/lija.webp", precio: "$39.850" },
    { nombre: "Sellador para madera", link: "https://meli.la/2HAQe8L", imagen: "/herramientas/sellador-madera.webp", precio: "$5.700" },
    { nombre: "Clavos y tornillos", link: "https://meli.la/2bHreCP", imagen: "/herramientas/clavos-tornillos.webp", precio: "$33.500" },
    { nombre: "Cola vinilica", link: "https://meli.la/13zfbLM", imagen: "/herramientas/cola-vinilica.webp", precio: "$7.425" },
    { nombre: "Serrucho", link: "https://meli.la/1bPXbCN", imagen: "/herramientas/serrucho.webp", precio: "$8.199" },
    { nombre: "Formon escoplo", link: "https://meli.la/1nPVAto", imagen: "/herramientas/formon.webp", precio: "$8.299" },
    { nombre: "Mechas para taladro", link: "https://meli.la/1zPp4bY", imagen: "/herramientas/mechas-taladro.webp", precio: "$11.900" },
    { nombre: "Taladro inalambrico", link: "https://meli.la/2X3w48o", imagen: "/herramientas/taladro-inalambrico.webp", precio: "$124.147" },
  ],
  pintura: [
    { nombre: "Rodillo de pintura", link: "https://meli.la/2zRu7tq", imagen: "/herramientas/rodillo.webp", precio: "$7.405" },
    { nombre: "Pincel", link: "https://meli.la/1a9zKnB", imagen: "/herramientas/pincel.webp", precio: "$57.041" },
    { nombre: "Cinta de enmascarar", link: "https://meli.la/2uEkY6B", imagen: "/herramientas/cinta-enmascarar.webp", precio: "$43.848" },
    { nombre: "Bandeja para pintura", link: "https://meli.la/1LGDSKU", imagen: "/herramientas/bandeja-pintura.webp", precio: "$5.052" },
    { nombre: "Masilla para paredes", link: "https://meli.la/2rgq3T6", imagen: "/herramientas/masilla.webp", precio: "$26.399" },
    { nombre: "Lija para pared", link: "https://meli.la/116VJhL", imagen: "/herramientas/lija-pared.webp", precio: "$8.250" },
    { nombre: "Fijador sellador pared", link: "https://meli.la/2Yz2UP4", imagen: "/herramientas/fijador-pared.webp", precio: "$29.000" },
    { nombre: "Espatula", link: "https://meli.la/1eZsoxM", imagen: "/herramientas/espatula.webp", precio: "$4.775" },
  ],
  humedad: [],
  electrodomesticos: [],
};
